export const CHECKOUT_URLS = { ESSENCIAL: 'https://app.zuptos.com.br/checkout/3964ebc0548af57e', COMPLETO: 'https://app.zuptos.com.br/checkout/58864c8277caafae', OFERTA_UPSELL: 'https://app.zuptos.com.br/checkout/e8d0547d33daa9bd' };
export const CAROUSEL_ITEMS = [
{id:1,title:'Algoritmos e Estruturas de Dados',imageSrc:'https://mapasmentaisciencia.netlify.app/images/mapa-algoritmos-estruturas.jpg',alt:'Mapa Mental de Algoritmos e Estruturas de Dados'},
{id:2,title:'Ciência da Computação',imageSrc:'https://mapasmentaisciencia.netlify.app/images/mapa-ciencia-computacao.jpg',alt:'Mapa Mental de Ciência da Computação'},
{id:3,title:'Estruturas de Dados',imageSrc:'https://mapasmentaisciencia.netlify.app/images/mapa-estruturas-dados.jpg',alt:'Mapa Mental de Estruturas de Dados'},
{id:4,title:'Redes de Computadores',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2013_34_30.png',alt:'Mapa Mental de Redes de Computadores'},
{id:5,title:'Modelo OSI & Protocolos',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2013_34_34.png',alt:'Mapa Mental do Modelo OSI'},
{id:6,title:'Banco de Dados',imageSrc:'https://mapasmentaisciencia.netlify.app/images/mapa-banco-dados.jpg',alt:'Mapa Mental de Banco de Dados'},
{id:7,title:'Bancos de Dados Relacionais',imageSrc:'https://mapasmentaisciencia.netlify.app/images/mapa-bancos-relacionais.jpg',alt:'Mapa Mental de Bancos de Dados Relacionais'},
{id:8,title:'Engenharia de Software',imageSrc:'https://mapasmentaisciencia.netlify.app/images/mapa-engenharia-software.jpg',alt:'Mapa Mental de Engenharia de Software'}];
export const BONUS_ITEMS = [
{id:1,title:'Mapa Visual de Big-O',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2011_10_29.png',alt:'Mapa visual de complexidade de algoritmos',description:'Referência visual para consultar complexidade de algoritmos e comparar desempenho.'},
{id:2,title:'Guia Visual de Siglas de TI',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2011_10_44.png',alt:'Guia visual de siglas de tecnologia',description:'Siglas, termos e conceitos organizados para revisão rápida.'},
{id:3,title:'Mapa de Comparativos',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2011_14_26.png',alt:'Mapas comparativos de conceitos de computação',description:'Comparações entre conceitos que costumam ser confundidos durante o estudo.'},
{id:4,title:'Checklist de Revisão',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2011_17_31.png',alt:'Checklist visual de revisão',description:'Lista organizada para acompanhar assuntos estudados e revisados.'},
{id:5,title:'Caderno Visual de Pegadinhas',imageSrc:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2011_18_51.png',alt:'Caderno visual de pegadinhas',description:'Diferenças, exceções e detalhes que merecem atenção na revisão.'}];
export const PRICING_PLANS = [
{id:'plano-essencial',title:'Material Essencial',subtitle:'+300 Mapas Mentais de Ciência da Computação',items:[{label:'+300 Mapas Mentais de Ciência da Computação'},{label:'9 grandes áreas de estudo'},{label:'Mapas organizados por assunto'},{label:'Acesso digital imediato'}],price:'R$ 10,00',priceNote:'Pagamento único. Sem mensalidade.',ctaId:'cta-oferta-basica',ctaHref:CHECKOUT_URLS.ESSENCIAL,ctaLabel:'Quero comprar',ctaVariant:'muted'},
{id:'plano-completo',featured:true,badge:'Mais Escolhido',title:'Plano Completo',mockupImage:'https://mapasmentaisciencia.netlify.app/images/ChatGPT%20Image%202%20de%20out.%20de%202026,%2010_45_59.png',mockupAlt:'Mockup do Plano Completo',items:[{label:'+300 Mapas Mentais de Ciência da Computação'},{label:'Arquitetura e Organização de Computadores'},{label:'Sistemas Operacionais'},{label:'Redes de Computadores'},{label:'Banco de Dados'},{label:'Engenharia de Software'},{label:'Mapa Visual de Big-O',bonus:true},{label:'Guia Visual de Siglas de TI',bonus:true},{label:'Mapa de Comparativos',bonus:true},{label:'Checklist de Revisão',bonus:true},{label:'Caderno Visual de Pegadinhas',bonus:true}],price:'R$ 27,00',priceNote:'Pagamento único. Sem mensalidade.',ctaId:'cta-pacote-completo',ctaHref:CHECKOUT_URLS.COMPLETO,ctaLabel:'Quero comprar',footnote:'Compra única • Acesso imediato • Garantia de 30 dias'}];
export const MODAL_INCLUSIONS = ['+300 Mapas Mentais de Ciência da Computação','9 grandes áreas de estudo','Arquitetura de Computadores','Sistemas Operacionais','Redes de Computadores','Banco de Dados','Engenharia de Software','Mapa Visual de Big-O','Guia Visual de Siglas de TI','Mapa de Comparativos','Checklist de Revisão','Caderno Visual de Pegadinhas'];
export const FAQS = [
{question:'O material é físico ou digital?',answer:'O material é 100% digital. Você recebe acesso ao conteúdo e pode consultar os mapas no celular, tablet ou computador.'},
{question:'O que existe dentro dos +300 mapas?',answer:'Os mapas são organizados por grandes áreas da Ciência da Computação, como algoritmos, estruturas de dados, arquitetura, sistemas operacionais, redes, banco de dados, engenharia de software, segurança e inteligência artificial.'},
{question:'Os mapas substituem um curso completo?',answer:'Não. A proposta é funcionar como uma biblioteca visual de estudo e revisão, ajudando a condensar e organizar conceitos para consulta rápida.'},
{question:'Posso usar os mapas para revisar antes de uma prova?',answer:'Sim. A estrutura foi pensada para consulta e revisão, facilitando a retomada de conceitos, comparações e pontos importantes.'},
{question:'Como recebo o acesso ao material?',answer:'Após a confirmação do pagamento, o acesso é liberado digitalmente conforme as instruções da plataforma de compra.'},
{question:'Posso estudar pelo celular?',answer:'Sim. O conteúdo foi organizado para ser consultado digitalmente em diferentes dispositivos.'},
{question:'Como funciona a garantia de 30 dias?',answer:'Você tem 30 dias para conhecer o material. Dentro das condições da plataforma de pagamento, poderá solicitar o reembolso caso o conteúdo não faça sentido para sua necessidade.'}];
export const RECENT_PURCHASES = [{nome:'Estudante de TI',cidade:'São Paulo, SP'},{nome:'Candidato de Tecnologia',cidade:'Belo Horizonte, MG'},{nome:'Estudante de Computação',cidade:'Curitiba, PR'},{nome:'Profissional de TI',cidade:'Recife, PE'},{nome:'Estudante de Tecnologia',cidade:'Porto Alegre, RS'}];
const ATTRIBUTION_KEY='mmse_attribution_params'; const ONE_DAY_MS=86400000;
export const getAttributionParams=()=>{if(typeof window==='undefined')return new URLSearchParams();try{const raw=window.sessionStorage.getItem(ATTRIBUTION_KEY)||window.localStorage.getItem(ATTRIBUTION_KEY);if(!raw)return new URLSearchParams();const data=JSON.parse(raw);if(!data?.query||!data?.capturedAt||Date.now()-data.capturedAt>ONE_DAY_MS)return new URLSearchParams();return new URLSearchParams(data.query)}catch{return new URLSearchParams()}};
export const captureAttribution=()=>{if(typeof window==='undefined')return;try{const params=new URLSearchParams(window.location.search);if([...params.keys()].length===0)return;const current=getAttributionParams();params.forEach((val,key)=>{if(val)current.set(key,val)});const payload=JSON.stringify({query:current.toString(),capturedAt:Date.now()});window.sessionStorage.setItem(ATTRIBUTION_KEY,payload);window.localStorage.setItem(ATTRIBUTION_KEY,payload)}catch{}};
export const appendAttribution=(url:string)=>{if(typeof window==='undefined'||(!url.startsWith('http://')&&!url.startsWith('https://')))return url;try{captureAttribution();const target=new URL(url);const stored=getAttributionParams();const current=new URLSearchParams(window.location.search);stored.forEach((val,key)=>{if(val&&!target.searchParams.has(key))target.searchParams.set(key,val)});current.forEach((val,key)=>{if(val)target.searchParams.set(key,val)});return target.toString()}catch{return url}};
export const trackCheckout=({contentName,value,currency='BRL'}:{contentName:string;value?:number;currency?:string})=>{if(typeof window==='undefined')return;const fbq=(window as any).fbq;if(typeof fbq!=='function')return;const payload:any={content_name:contentName,content_type:'product',currency};if(typeof value==='number')payload.value=value;try{fbq('track','InitiateCheckout',payload)}catch{}};
